//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTDI_Gate_Log
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vtdi_Gate_DatabaseEntities : DbContext
    {
        public Vtdi_Gate_DatabaseEntities()
            : base("name=Vtdi_Gate_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Declare> Declares { get; set; }
        public virtual DbSet<GateInOut> GateInOuts { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Purpose> Purposes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vehicleType> vehicleTypes { get; set; }
    }
}
